ProjectName = String

ROOT = ./../../../../

-include $(ROOT)make/makefile.DefPath.mk

-include $(ROOT)make/makefile.Def.mk

cppfiles   :=

cppfiles   += $(SOURCE)String.cpp



hpaths    := 
hpaths    += $(INCLUDE)
hpaths    += $(ROOT)

lpaths    := 
lpaths    += $(LIB)

defines   := 


libraries := 





-include $(ROOT)make/makefile.Lib.mk

