ProjectName = Math

ROOT        = ./../../../../
SOURCE      = ./../../
LIB         = ./../../../Lib/linux64/

FILE        = makefile

-include $(ROOT)make/makefile.Def.mk

cppfiles   :=
cppfiles   += $(SOURCE)Vec3.cpp
cppfiles   += $(SOURCE)Vec4.cpp
cppfiles   += $(SOURCE)Mat33.cpp
cppfiles   += $(SOURCE)Mat44.cpp
cppfiles   += $(SOURCE)Transform.cpp

hpaths    := 
hpaths    += ./../../../Include

lpaths    := 

defines   := 

libraries := 

-include $(ROOT)make/makefile.Lib.mk

