root      := ./../../../

hpaths    := 
hpaths    += $(root)boost_1_54_0/

lpaths    := $(root)boost_1_54_0/stage/lib/

defines   := 
defines   += __DEBUG__
defines   += __LINUX
defines   += __OPENGL

libraries := 
libraries += pthread


-include $(root)make/makefile.Lib.mk





