ProjectName = StackTrace

ROOT        = ./../../../../
SOURCE      = ./../../
LIB         = ./../../../Lib/

-include $(ROOT)make/makefile.Def.mk

cppfiles   :=
cppfiles   += $(SOURCE)ArrayDeleter.cpp

hpaths    := 
hpaths    += ./../../../Include

lpaths    := 

defines   := 

libraries := 

bin      := $(LIB)linux64/libArrayDeleter.a

-include $(ROOT)make/makefile.Lib.mk

