ProjectName = StackTrace

ROOT = ./../../../../

-include $(ROOT)make/makefile.DefPath.mk

-include $(ROOT)make/makefile.Def.mk

cppfiles   :=
cppfiles   += $(SOURCE)StackTrace.cpp

hpaths    := 
hpaths    += ./../../../Include

lpaths    := 

defines   := 
defines   += __LINUX


libraries := 

bin      := $(LIB)linux64/libStackTrace.a

-include $(ROOT)make/makefile.Lib.mk



